@echo off
cd /d "C:\Users\guede\CascadeProjects\dog-hotel-app"
echo Adicionando arquivos...
git add -A
echo Fazendo commit...
git commit -m "Melhorias ficha do monitor: refeições, atividades, humor, medicação, observações"
echo Enviando para o repositório...
git push origin main
echo.
echo Pressione qualquer tecla para fechar...
pause >nul
