import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

const INAUGURATION_DATE = new Date('2026-02-07')

function period(dateStr: string): string {
  const d = new Date(dateStr)
  return d < INAUGURATION_DATE
    ? 'PRE_INAUGURACAO'
    : `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
}

// Historical data from spreadsheet
const HISTORICAL_DATA = [
  { type: 'S', date: '2025-12-04', amount: 139, account: 'SEBÁ', supplier: 'ÁGIL CONT.', description: 'ABERTURA - MENSALIDADE', category: 'CONTABILIDADE' },
  { type: 'S', date: '2025-12-07', amount: 418.56, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-07', amount: 1497.12, account: 'VÊ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-10', amount: 336.4, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-10', amount: 1137.11, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2025-12-10', amount: 3000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2025-12-11', amount: 211.01, account: 'SEBÁ', supplier: 'ÁGIL CONT.', description: 'TAXA JUNTA COMERCIAL', category: 'TAXA JUNTA COMERCIAL' },
  { type: 'E', date: '2025-12-11', amount: 4000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2025-12-11', amount: 3015.83, account: 'SEBÁ', supplier: 'OSASFERRO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-12', amount: 1188.18, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-13', amount: 227.5, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-13', amount: 130.87, account: 'SEBÁ', supplier: 'MARMITA', description: 'ALIMENTAÇÃO PEDREIROS', category: 'OUTROS' },
  { type: 'S', date: '2025-12-13', amount: 102.8, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-15', amount: 1000, account: 'VÊ', supplier: 'SIDEVANDO', description: 'PEDREIRO', category: 'OBRA' },
  { type: 'S', date: '2025-12-15', amount: 756, account: 'SEBÁ', supplier: 'OSASFERRO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-15', amount: 97, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2025-12-16', amount: 5000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2025-12-16', amount: 1175, account: 'SEBÁ', supplier: 'DESTAK', description: 'FACHADA', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2025-12-16', amount: 1500, account: 'SEBÁ', supplier: 'FRANK', description: 'SERRALHEIRO', category: 'OBRA' },
  { type: 'S', date: '2025-12-16', amount: 244, account: 'SEBÁ', supplier: 'OSASFERRO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-16', amount: 261.52, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-17', amount: 124, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-17', amount: 399.65, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-17', amount: 900.93, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-19', amount: 1175, account: 'SEBÁ', supplier: 'DESTAK', description: 'FACHADA', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'E', date: '2025-12-19', amount: 2000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2025-12-22', amount: 156, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-22', amount: 92, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-22', amount: 40, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-22', amount: 1000, account: 'SEBÁ', supplier: 'SIDEVANDO', description: 'PEDREIRO', category: 'OBRA' },
  { type: 'S', date: '2025-12-22', amount: 1023.6, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-22', amount: 54, account: 'SEBÁ', supplier: 'MINA DE OURO', description: 'MATERIAL', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2025-12-22', amount: 334, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-23', amount: 210, account: 'VÊ', supplier: 'CESTAS PINTORES', description: 'OUTROS', category: 'OBRA' },
  { type: 'S', date: '2025-12-23', amount: 100, account: 'VÊ', supplier: 'ASSINATURA', description: 'MAQUININHA DO CARTÃO', category: 'SISTEMA CARTÃO' },
  { type: 'E', date: '2025-12-24', amount: 4000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2025-12-26', amount: 1408, account: 'SEBÁ', supplier: 'CORANTE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2025-12-26', amount: 2500, account: 'SEBÁ', supplier: 'PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'S', date: '2025-12-26', amount: 100, account: 'SEBÁ', supplier: 'REMOÇÃO SOFÁ', description: 'OUTROS', category: 'OBRA' },
  { type: 'S', date: '2025-12-30', amount: 1173, account: 'SEBÁ', supplier: 'CORANTE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-02', amount: 2000, account: 'SEBÁ', supplier: 'ADIANTAMENTO PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'S', date: '2026-01-02', amount: 750, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2026-01-05', amount: 6000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-01-07', amount: 936, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-07', amount: 590, account: 'SEBÁ', supplier: 'AVCB', description: 'ALVARÁ', category: 'TAXA BOMBEIROS' },
  { type: 'S', date: '2026-01-07', amount: 60, account: 'SEBÁ', supplier: 'ASSOCIAÇÃO', description: 'OUTROS', category: 'ASSOCIAÇÃO' },
  { type: 'S', date: '2026-01-08', amount: 300, account: 'SEBÁ', supplier: 'LOCATOM', description: 'ANDAIMES', category: 'OBRA' },
  { type: 'S', date: '2026-01-09', amount: 2000, account: 'SEBÁ', supplier: 'PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'S', date: '2026-01-09', amount: 80, account: 'SEBÁ', supplier: 'PINTORES', description: 'GRATIFICAÇÃO', category: 'OBRA' },
  { type: 'S', date: '2026-01-09', amount: 140, account: 'SEBÁ', supplier: 'TRANSPORTE PALLETES', description: 'TRANSPORTE PALLETES', category: 'OUTROS' },
  { type: 'S', date: '2026-01-09', amount: 540, account: 'SEBÁ', supplier: 'PALLETE', description: 'INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-01-09', amount: 506.32, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-10', amount: 60, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-10', amount: 52.35, account: 'VÊ', supplier: 'MOLDES', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-01-12', amount: 139, account: 'SEBÁ', supplier: 'CONTABILIDADE', description: 'CONTABILIDADE', category: 'CONTABILIDADE' },
  { type: 'S', date: '2026-01-12', amount: 400, account: 'SEBÁ', supplier: 'SIDEVANDO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-13', amount: 128, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-14', amount: 355, account: 'SEBÁ', supplier: 'CORANTE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-14', amount: 1000, account: 'SEBÁ', supplier: 'SIDEVANDO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-14', amount: 233.04, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2026-01-15', amount: 7000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-01-15', amount: 6, account: 'SEBÁ', supplier: 'CORANTE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-16', amount: 6000, account: 'SEBÁ', supplier: 'ELAINE', description: 'ALUGUEL', category: 'ALUGUEL' },
  { type: 'S', date: '2026-01-17', amount: 1042.57, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-17', amount: 626.86, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-17', amount: 221.8, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-17', amount: 49.6, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-17', amount: 151, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-19', amount: 2000, account: 'SEBÁ', supplier: 'PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'E', date: '2026-01-19', amount: 5000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-01-20', amount: 1553, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-20', amount: 218, account: 'SEBÁ', supplier: 'SIDEVANDO', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-20', amount: 249.85, account: 'VÊ', supplier: 'GRÁFICA TEXTIL', description: 'JAPAN', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-01-22', amount: 47.7, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-22', amount: 254.4, account: 'SEBÁ', supplier: 'SODIMAC', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-22', amount: 1079.26, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-22', amount: 114.81, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-22', amount: 206, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2026-01-22', amount: 3000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-01-23', amount: 651.77, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-23', amount: 30, account: 'VÊ', supplier: 'GRÁFICA TEXTIL', description: 'JAPAN', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-01-24', amount: 1400, account: 'SEBÁ', supplier: 'PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'S', date: '2026-01-24', amount: 1000, account: 'VÊ', supplier: 'PINTORES', description: 'PINTORES', category: 'OBRA' },
  { type: 'S', date: '2026-01-24', amount: 57.08, account: 'VÊ', supplier: 'OUTROS', description: 'OUTROS', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-01-26', amount: 420, account: 'SEBÁ', supplier: 'CAÇAMBA', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-26', amount: 206, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-26', amount: 47.88, account: 'VÊ', supplier: 'PAGBANK', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-01-27', amount: 1340, account: 'SEBÁ', supplier: 'LEROY', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2026-01-27', amount: 1500, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-01-28', amount: 355, account: 'SEBÁ', supplier: 'CORANTE', description: 'MATERIAL', category: 'OBRA' },
  { type: 'S', date: '2026-01-29', amount: 100, account: 'SEBÁ', supplier: 'MARQUES', description: 'MATERIAL', category: 'OBRA' },
  { type: 'E', date: '2026-01-29', amount: 1500, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-02', amount: 232.27, account: 'SEBÁ', supplier: 'MATERIAL PET', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 453.18, account: 'SEBÁ', supplier: 'MATERIAL PET', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 211.79, account: 'VÊ', supplier: 'MATERIAL PET', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 1551, account: 'VÊ', supplier: 'MATERIAL PET', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 15, account: 'VÊ', supplier: 'MATERIAL PET', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'E', date: '2026-02-02', amount: 3000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-02', amount: 1000, account: 'SEBÁ', supplier: 'PINTORES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-02', amount: 1000, account: 'SEBÁ', supplier: 'PINTORES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-02', amount: 784.09, account: 'SEBÁ', supplier: 'LEROY', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-02', amount: 439.96, account: 'SEBÁ', supplier: 'CASULO', description: 'ITENS INAUGURAÇÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 1664.3, account: 'VÊ', supplier: 'LEROY', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-02', amount: 75.7, account: 'VÊ', supplier: 'KALUNGA', description: 'MATERIAL FACHADA E INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 97.5, account: 'VÊ', supplier: 'TECIDO', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-02', amount: 49.97, account: 'VÊ', supplier: 'CAMISETA', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-03', amount: 449.5, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL GERAL', category: 'MATERIAL LIMPEZA' },
  { type: 'S', date: '2026-02-03', amount: 17, account: 'SEBÁ', supplier: 'KALUNGA', description: 'MATERIAL CAMISETA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-03', amount: 220, account: 'SEBÁ', supplier: 'SMART MADEIRAS', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-03', amount: 2515.37, account: 'VÊ', supplier: 'LEROY', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-03', amount: 903.52, account: 'VÊ', supplier: 'ATACADÃO', description: 'ITENS INAUGURAÇÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-04', amount: 398, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-04', amount: 180, account: 'VÊ', supplier: 'JOSENOR', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-04', amount: 1288.92, account: 'VÊ', supplier: 'NEON', description: 'NEON INSTAGRAMAVEL', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-04', amount: 86.4, account: 'VÊ', supplier: 'QR CODE PAREDE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 223, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-05', amount: 213, account: 'SEBÁ', supplier: 'MADEREIRA SANTANA', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-05', amount: 128.5, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 140, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 69.58, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 62.99, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 117.8, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 269.18, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-05', amount: 66.49, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'E', date: '2026-02-06', amount: 1000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-06', amount: 145.2, account: 'SEBÁ', supplier: 'JAPA ADESIVOS', description: 'ADESIVOS GELADEIRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-06', amount: 150, account: 'SEBÁ', supplier: 'CORANTE', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-06', amount: 509.55, account: 'SEBÁ', supplier: 'MADEREIRA SANTANA', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-06', amount: 88, account: 'VÊ', supplier: 'CASA DE BOLO', description: 'INAUGURAÇÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-06', amount: 33.8, account: 'VÊ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-07', amount: 1559.84, account: 'SEBÁ', supplier: 'PINTORES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-07', amount: 105, account: 'SEBÁ', supplier: 'LU FLORES', description: 'ITENS INAUGURAÇÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-07', amount: 80, account: 'VÊ', supplier: 'PÃO MEL', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-08', amount: 104.79, account: 'SEBÁ', supplier: 'GARDEN', description: '01/05', category: 'OBRA' },
  { type: 'S', date: '2026-02-08', amount: 104.79, account: 'SEBÁ', supplier: 'GARDEN', description: '2/5', category: 'OBRA' },
  { type: 'S', date: '2026-02-08', amount: 104.79, account: 'SEBÁ', supplier: 'GARDEN', description: '3/5', category: 'OBRA' },
  { type: 'S', date: '2026-02-08', amount: 104.79, account: 'SEBÁ', supplier: 'GARDEN', description: '04/5', category: 'OBRA' },
  { type: 'E', date: '2026-02-09', amount: 3000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-09', amount: 145.58, account: 'SEBÁ', supplier: 'CADEIRAS', description: 'INAUGURAÇÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-09', amount: 117, account: 'VÊ', supplier: 'FUNCIONÁRIO', description: 'NATALIA', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-02-09', amount: 70, account: 'VÊ', supplier: 'FUNCIONÁRIO', description: 'MARIA', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-02-09', amount: 100, account: 'VÊ', supplier: 'FUNCIONÁRIO', description: 'NATALIA', category: 'FOLHA SALARIAL' },
  { type: 'E', date: '2026-02-10', amount: 500, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-10', amount: 416.59, account: 'SEBÁ', supplier: 'MUDANÇA', description: '', category: 'OUTROS' },
  { type: 'S', date: '2026-02-10', amount: 17.2, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-11', amount: 350, account: 'SEBÁ', supplier: 'OUTROS', description: 'PAULINHO', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-02-12', amount: 148, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'E', date: '2026-02-13', amount: 1000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-13', amount: 300.76, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'LUMINÁRIAS NEON+CORTADORES', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-14', amount: 52.7, account: 'VÊ', supplier: 'PIRUETA', description: '', category: 'INFRAESTRUTURA' },
  { type: 'E', date: '2026-02-18', amount: 4000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-02-18', amount: 1000, account: 'SEBÁ', supplier: 'ELAINE', description: '', category: 'ALUGUEL' },
  { type: 'S', date: '2026-02-18', amount: 459.41, account: 'SEBÁ', supplier: 'FUNCIONÁRIO', description: 'NATALIA', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-02-18', amount: 161.48, account: 'SEBÁ', supplier: 'SABESP', description: '', category: 'ÁGUA' },
  { type: 'S', date: '2026-02-19', amount: 85.86, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-02-20', amount: 5000, account: 'SEBÁ', supplier: 'ELAINE', description: '', category: 'ALUGUEL' },
  { type: 'S', date: '2026-02-20', amount: 50, account: 'SEBÁ', supplier: 'CORANTE', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-20', amount: 111.49, account: 'SEBÁ', supplier: 'ENEL', description: 'ENERGIA ELÉTRICA', category: 'ENERGIA ELÉTRICA' },
  { type: 'S', date: '2026-02-20', amount: 100, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-02-26', amount: 192.67, account: 'SEBÁ', supplier: '360 IMPRIMIR', description: 'PANFLETOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-02-26', amount: 60, account: 'SEBÁ', supplier: 'ABCC', description: 'ASSOCIAÇÃO CRECHES CANINAS', category: 'ASSOCIAÇÃO' },
  { type: 'S', date: '2026-02-26', amount: 73, account: 'SEBÁ', supplier: 'JUCESP', description: '', category: 'TAXA JUNTA COMERCIAL' },
  { type: 'S', date: '2026-03-01', amount: 93.63, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'CORTINAS', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-01', amount: 1464.56, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'CARTÃO INÍCIO OPERAÇÃO', category: 'PROLABORE' },
  { type: 'E', date: '2026-03-03', amount: 600, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'E', date: '2026-03-03', amount: 1000, account: 'NICE', supplier: '', description: '', category: 'APORTE SÓCIOS' },
  { type: 'S', date: '2026-03-03', amount: 344.41, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-03', amount: 108.88, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'LUMINÁRIAS NEON 2/9', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-04', amount: 34.23, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MOUSE', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-05', amount: 94.88, account: 'VÊ', supplier: 'CLARO', description: 'INTERNET', category: 'INTERNET' },
  { type: 'S', date: '2026-03-06', amount: 434.42, account: 'SEBÁ', supplier: 'FUNCIONÁRIO', description: 'SARAH', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-03-06', amount: 424.09, account: 'SEBÁ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-03-07', amount: 122, account: 'SEBÁ', supplier: 'MARQUES', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-03-09', amount: 46.4, account: 'VÊ', supplier: 'KALUNGA', description: 'MATERIAL CAMISETA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-10', amount: 33.8, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-11', amount: 26.9, account: 'SEBÁ', supplier: 'LOCAWEB', description: 'SITE', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-03-11', amount: 149.3, account: 'VÊ', supplier: 'JAPAN GRÁFICA', description: 'CAMISETAS', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-16', amount: 413.15, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-16', amount: 53.7, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-17', amount: 123.89, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-17', amount: 30.98, account: 'SEBÁ', supplier: 'OZ PET', description: 'POTE BARUC', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-18', amount: 63.28, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-21', amount: 169.89, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'MATERIAL INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-21', amount: 148.71, account: 'SEBÁ', supplier: 'SODIMAC', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-03-23', amount: 88.59, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-03-23', amount: 48.77, account: 'VÊ', supplier: 'SHOPPEE', description: 'PASCOA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-24', amount: 42.25, account: 'AUÊ', supplier: 'MARQUES', description: 'MATERIAL INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-03-25', amount: 142, account: 'AUÊ', supplier: 'CONTABILIDADE', description: '', category: 'CONTABILIDADE' },
  { type: 'S', date: '2026-03-26', amount: 383.19, account: 'AUÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-03-26', amount: 260.09, account: 'SEBÁ', supplier: 'GOOGLE AD', description: '', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-03-26', amount: 103.56, account: 'VÊ', supplier: 'SHOPPEE', description: 'PASCOA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-26', amount: 60.23, account: 'VÊ', supplier: 'CARREFOUR', description: 'ITENS PASCOA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-26', amount: 28.26, account: 'VÊ', supplier: 'MINI EXTRA', description: 'ITENS PASCOA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-26', amount: 271.96, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'COMPRA ML', category: 'PROLABORE' },
  { type: 'S', date: '2026-03-28', amount: 11.77, account: 'AUÊ', supplier: 'TROPICAL', description: 'COMPRA MERCADO', category: 'MATERIAL LIMPEZA' },
  { type: 'S', date: '2026-03-28', amount: 11.51, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'PÃO PARQUE', category: 'PROLABORE' },
  { type: 'S', date: '2026-03-28', amount: 235.1, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'RAÇÃO FILHOTES', category: 'PROLABORE' },
  { type: 'S', date: '2026-03-28', amount: 29.9, account: 'AUÊ', supplier: 'PETZ', description: 'PETISCOS', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 49.2, account: 'AUÊ', supplier: 'PALÁDIO', description: 'MATERIAL INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-03-30', amount: 85, account: 'AUÊ', supplier: 'TELEFÔNICA (VIVO)', description: 'TELEFONE', category: 'INTERNET' },
  { type: 'S', date: '2026-03-30', amount: 56, account: 'AUÊ', supplier: 'MARQUES', description: 'MATERIAL INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-03-30', amount: 55, account: 'AUÊ', supplier: 'SODIMAC', description: 'MATERIAL INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-03-30', amount: 50.34, account: 'VÊ', supplier: 'SHOPPEE', description: '1/3', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 25, account: 'VÊ', supplier: 'SHOPPEE', description: 'PASCOA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 63.96, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 479.55, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'BANHO & TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 190.69, account: 'VÊ', supplier: 'MERCADO LIVRE', description: '1/10 BANHO & TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 36.9, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'PLACA EVA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-03-30', amount: 59, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'TELEFONE', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-01', amount: 161.48, account: 'AUÊ', supplier: 'SABESP', description: '', category: 'ÁGUA' },
  { type: 'S', date: '2026-04-01', amount: 34.21, account: 'AUÊ', supplier: 'ENEL', description: '', category: 'ENERGIA ELÉTRICA' },
  { type: 'S', date: '2026-04-01', amount: 30, account: 'AUÊ', supplier: 'AUTOZONE', description: 'SPRAY ROSA', category: 'OBRA' },
  { type: 'S', date: '2026-04-01', amount: 24.19, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'ENEL CASA', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-01', amount: 125.56, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'ENEL CASA', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-02', amount: 37.58, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-02', amount: 45.97, account: 'VÊ', supplier: 'MERCADO LIVRE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-02', amount: 49.5, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'CONTA LUZ CASA', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-02', amount: 25.31, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'ENEL CASA', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-02', amount: 153.95, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'AUTOZONE', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-02', amount: 150, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'GASOLINA PAJERO', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-02', amount: 199.97, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'OVOS FILHOS SEBÁ', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-03', amount: 108.88, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'LUMINÁRIAS NEON 3/9', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-07', amount: 303.01, account: 'AUÊ', supplier: 'ENEL', description: '', category: 'ENERGIA ELÉTRICA' },
  { type: 'S', date: '2026-04-07', amount: 101.49, account: 'AUÊ', supplier: 'ENEL', description: '', category: 'ENERGIA ELÉTRICA' },
  { type: 'S', date: '2026-04-07', amount: 100, account: 'VÊ', supplier: 'ATIVIDADES PARA PROVENTOS', description: '', category: 'OUTROS' },
  { type: 'S', date: '2026-04-08', amount: 2197.34, account: 'AUÊ', supplier: 'SALÁRIO SARAH', description: '', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-04-08', amount: 1700, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'PENSÃO CRIANÇAS - LANÇADO', category: 'PROLABORE' },
  { type: 'S', date: '2026-04-08', amount: 82.05, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-08', amount: 350.55, account: 'VÊ', supplier: 'PETZ', description: 'PRODUTOS DE LIMPEZA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-10', amount: 50, account: 'AUÊ', supplier: 'PERNOITE', description: 'SARAH', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-04-11', amount: 61.08, account: 'SEBÁ', supplier: 'LEROY MERLIN', description: '', category: 'OBRA' },
  { type: 'S', date: '2026-04-12', amount: 189.95, account: 'SEBÁ', supplier: 'AUTOZONE', description: 'SPRAYS TUNEL', category: 'OBRA' },
  { type: 'S', date: '2026-04-12', amount: 167.39, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-14', amount: 344.97, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-15', amount: 6000, account: 'VÊ', supplier: 'ALUGUEL', description: '', category: 'ALUGUEL' },
  { type: 'S', date: '2026-04-17', amount: 167.47, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-19', amount: 46, account: 'VÊ', supplier: 'SHOPPEE', description: 'CORAÇÃO MÃES', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-21', amount: 36.9, account: 'VÊ', supplier: 'SHOPPEE', description: 'POTE RAMIRO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-22', amount: 167.33, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-23', amount: 327.92, account: 'AUÊ', supplier: 'SABESP', description: '', category: 'ÁGUA' },
  { type: 'S', date: '2026-04-24', amount: 62.97, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-24', amount: 297.08, account: 'SEBÁ', supplier: 'MERCADO LIVRE', description: 'INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-25', amount: 34.98, account: 'VÊ', supplier: 'SHOPPEE', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-25', amount: 34.88, account: 'VÊ', supplier: 'SHOPPEE', description: 'MORDEDOR SIRIUS', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-26', amount: 167.45, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-04-27', amount: 406.78, account: 'SEBÁ', supplier: 'SODIMAC', description: 'INFRA', category: 'OBRA' },
  { type: 'S', date: '2026-04-27', amount: 33.68, account: 'VÊ', supplier: 'SHOPPEE', description: 'MAQUINA TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-27', amount: 31.9, account: 'VÊ', supplier: 'SHOPPEE', description: 'BANHO E TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-27', amount: 39.99, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-27', amount: 56.99, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-28', amount: 100, account: 'AUÊ', supplier: 'LOCATOM', description: 'ESCADA', category: 'OBRA' },
  { type: 'S', date: '2026-04-30', amount: 50.34, account: 'VÊ', supplier: 'SHOPPEE', description: '02/03', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-30', amount: 37.69, account: 'VÊ', supplier: 'SHOPPEE', description: 'BANHO E TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-30', amount: 50.34, account: 'VÊ', supplier: 'SHOPPEE', description: '2/3', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-04-30', amount: 190.69, account: 'VÊ', supplier: 'MERCADO LIVRE', description: '2/10 BANHO & TOSA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-01', amount: 237.15, account: 'AUÊ', supplier: 'MERCADO LIVRE', description: 'ROTEADOR', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-03', amount: 108.88, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'LUMINÁRIAS NEON 4/9', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 105.52, account: 'AUÊ', supplier: 'MERCADO LIVRE', description: 'CAMERA COZINHA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 36.59, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 14.25, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 17.99, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 24, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-04', amount: 30, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-05', amount: 217, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'CARTÃO', category: 'PROLABORE' },
  { type: 'S', date: '2026-05-05', amount: 79.9, account: 'AUÊ', supplier: 'MERCADO LIVRE', description: 'CARTÃO CAMERA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-05', amount: 120, account: 'VÊ', supplier: 'CLARO', description: 'INTERNET', category: 'INTERNET' },
  { type: 'S', date: '2026-05-05', amount: 44.45, account: 'VÊ', supplier: 'SHOPPEE', description: 'MATERIAL COPA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-05', amount: 11, account: 'VÊ', supplier: 'SHOPPEE', description: 'MATERIAL COPA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-07', amount: 2151.85, account: 'AUÊ', supplier: 'SALÁRIO SARAH', description: '', category: 'FOLHA SALARIAL' },
  { type: 'S', date: '2026-05-08', amount: 44.1, account: 'VÊ', supplier: 'SHOPPEE', description: 'GRAVATINHA BORBOLETA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-08', amount: 78.17, account: 'VÊ', supplier: 'WINDSURF', description: 'IA INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-11', amount: 283.82, account: 'VÊ', supplier: 'BIOBONE', description: 'BRINQUEDOS CÃES BIOBONE', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-11', amount: 63, account: 'VÊ', supplier: 'IMPRESSÃO FOTOS DIA DAS MÃES', description: 'NEWCOPY', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-11', amount: 102.73, account: 'VÊ', supplier: 'WINDSURF', description: 'IA INFRA', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-12', amount: 62.68, account: 'VÊ', supplier: 'CACAUSHOW', description: 'DIA DAS MÃES', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-13', amount: 360, account: 'VÊ', supplier: 'CHICTOSA', description: 'APETRECHOS CÃES', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-13', amount: 29.38, account: 'VÊ', supplier: 'FACEBOOK', description: 'ANÚNCIOS', category: 'COMUNICAÇÃO E MARKETING' },
  { type: 'S', date: '2026-05-13', amount: 284.1, account: 'AUÊ', supplier: 'CONTABILIDADE', description: '', category: 'CONTABILIDADE' },
  { type: 'S', date: '2026-05-14', amount: 48.15, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'KIT ANIVERSÁRIO LEÃO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-14', amount: 30.9, account: 'VÊ', supplier: 'SHOPPEE', description: 'ANIVERSÁRIO LEO', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-15', amount: 6000, account: 'AUÊ', supplier: 'ALUGUEL', description: '', category: 'ALUGUEL' },
  { type: 'S', date: '2026-05-15', amount: 295.85, account: 'AUÊ', supplier: 'RETIRADA SEBÁ', description: 'SEM PARAR SÍTIO', category: 'PROLABORE' },
  { type: 'S', date: '2026-05-18', amount: 40.4, account: 'VÊ', supplier: 'MERCADO LIVRE', description: 'FAIXAS BRASIL', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-19', amount: 692.7, account: 'AUÊ', supplier: 'IPTU FEV', description: '', category: 'IMPOSTO IPTU' },
  { type: 'S', date: '2026-05-19', amount: 683.22, account: 'AUÊ', supplier: 'IPTU MAR', description: '', category: 'IMPOSTO IPTU' },
  { type: 'S', date: '2026-05-19', amount: 699.51, account: 'AUÊ', supplier: 'IPTU JAN', description: '', category: 'IMPOSTO IPTU' },
  { type: 'S', date: '2026-05-19', amount: 598.86, account: 'AUÊ', supplier: 'IPTU ABR', description: '', category: 'IMPOSTO IPTU' },
  { type: 'S', date: '2026-05-19', amount: 522.5, account: 'AUÊ', supplier: 'MULTPET', description: '', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-19', amount: 239.95, account: 'AUÊ', supplier: 'FEITO FILHO', description: 'MATERIAL CÃES', category: 'INFRAESTRUTURA' },
  { type: 'S', date: '2026-05-19', amount: 105.66, account: 'AUÊ', supplier: 'RETIRADA VERÔNICA', description: '', category: 'PROLABORE' },
  { type: 'S', date: '2026-05-19', amount: 29.9, account: 'AUÊ', supplier: 'ESTACIONAMENTO', description: '', category: 'OUTROS' },
  { type: 'S', date: '2026-05-19', amount: 120.22, account: 'AUÊ', supplier: 'SABESP', description: '', category: 'ÁGUA' },
  { type: 'S', date: '2026-05-19', amount: 342.19, account: 'AUÊ', supplier: 'ENEL', description: '', category: 'ENERGIA ELÉTRICA' },
]

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions)
  if (!session) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 })

  // Check if already seeded
  const existing = await prisma.financialEntry.count()
  if (existing > 0) {
    return NextResponse.json({ error: 'Dados já importados. Delete os registros primeiro.' }, { status: 409 })
  }

  const data = HISTORICAL_DATA.map(row => ({
    type: row.type,
    date: new Date(row.date),
    amount: row.amount,
    account: row.account,
    supplier: row.supplier || null,
    description: row.description || null,
    category: row.category,
    period: period(row.date),
    notes: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  }))

  await prisma.financialEntry.createMany({ data })

  return NextResponse.json({ imported: data.length })
}
