// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const updates: Array<{ matricula: string; data: Record<string, unknown> }> = [
  {
    matricula: 'H001',
    data: {
      name: 'Sol',
      ownerName: 'Carla Sato',
      ownerPhone: '11991289694',
      ownerEmail: 'Carla.akemi.sato@gmail.com',
      ownerCpf: '36704848843',
      breed: 'Border Collie',
      sex: 'femea',
      castrated: true,
      temperament: 'media-energia',
      size: 'medio',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '160',
      preferredActivities: 'Correr e pegar bolinha',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Hotel',
    },
  },
  {
    matricula: 'C001',
    data: {
      name: 'Dory',
      ownerName: 'Valéria Bellato',
      ownerPhone: '11947746229',
      ownerEmail: 'bellato.consultora@gmail.com',
      ownerCpf: '031.162.158-98',
      breed: 'Lhasa Apso',
      sex: 'femea',
      castrated: true,
      temperament: 'muita-energia',
      size: 'medio',
      feedingType: 'mista',
      feedingInstructions: 'Café da manhã: melão (1 fatia) ou batata doce (80gr). Almoço: ração seca (50grs)',
      feedingTimesPerDay: '1 vez',
      feedingGramsPerMeal: '50',
      preferredActivities: 'Tudo que imaginar',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Terça',
    },
  },
  {
    matricula: 'C002',
    data: {
      name: 'Sirius Black',
      ownerName: 'Aline Porto Gomes',
      ownerPhone: '11982356063',
      ownerEmail: 'portogomesaline@gmail.com',
      ownerCpf: '42131396899',
      breed: 'Pug',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'pequeno',
      medications: 'Olhinho operado — enxerga menos, precisa de colírio todos os dias',
      allergies: 'Perfume direto na pele (barriga, pescoço)',
      feedingType: 'mista',
      feedingInstructions: 'Ele come 50g de ração com franguinho desfiado 2x ao dia',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '50',
      preferredActivities: 'Buscar brinquedos',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche + Hotel',
      scheduledDays: 'Quarta',
    },
  },
  {
    matricula: 'H002',
    data: {
      name: 'Luna',
      ownerName: 'Tassia Gomes Jardim Brandão',
      ownerPhone: '11971572749',
      ownerEmail: 'tassiagj@gmail.com',
      ownerCpf: '35680254859',
      breed: 'Maltês',
      sex: 'femea',
      castrated: true,
      temperament: 'media-energia',
      size: 'pequeno',
      medications: 'Dermatite atópica — Zenrelia 1/2 comprimido/dia no jantar (junto com pedaço de pão)',
      feedingType: 'mista',
      feedingInstructions: 'Três refeições: 8h, 12h e 20h. Porção de um scoop cheio em cada refeição.',
      feedingTimesPerDay: '3 vezes',
      feedingGramsPerMeal: '25',
      preferredActivities: 'Buscar bolinha e muito chamego',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche + Hotel',
      scheduledDays: 'Segunda, Terça, Quarta, Quinta, Sexta, Sábado',
    },
  },
  {
    matricula: 'D001',
    data: {
      name: 'Baruc',
      ownerName: 'Debora Cristina Dantas de Sousa',
      ownerPhone: '11940145681',
      ownerEmail: 'deboracdantas88@gmail.com',
      ownerCpf: '35382667861',
      breed: 'Golden Retriever',
      sex: 'macho',
      castrated: true,
      temperament: 'media-energia',
      size: 'medio',
      medications: 'Alergia atópica',
      allergies: 'Alimentar',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '240',
      preferredActivities: 'Jogar brinquedo, puxar corda, se esconder depois que jogar o brinquedo, correr, puxar a guia, empurra-empurra',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche + Hotel',
      scheduledDays: 'Quarta, Quinta',
    },
  },
  {
    matricula: 'C003',
    data: {
      name: 'Theodoro',
      ownerName: 'Vitória Peres Cobo Koyama',
      ownerPhone: '11971269888',
      ownerEmail: 'vickoyama22@gmail.com',
      ownerCpf: '431.548.198-00',
      breed: 'Shih Tzu',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'pequeno',
      medications: 'Obesidade',
      feedingType: 'racao_seca',
      feedingInstructions: 'Ração específica para obesidade',
      feedingTimesPerDay: '3 vezes',
      feedingGramsPerMeal: '100',
      preferredActivities: 'Buscar bolinha, correr, morder',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Terça, Quinta',
    },
  },
  {
    matricula: 'C004',
    data: {
      name: 'Romain',
      ownerName: 'Gabriel Montanher',
      ownerPhone: '11954879133',
      ownerEmail: 'gabriel.montanher@icloud.com',
      ownerCpf: '4126251138',
      breed: 'SRD',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      allergies: 'Formigas',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '1 vez',
      feedingGramsPerMeal: '200',
      preferredActivities: 'Buscar bolinha, mordedores e pular',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Quarta, Sexta',
    },
  },
  {
    matricula: 'C005',
    data: {
      name: 'Theo',
      ownerName: 'Gabriel Montanher',
      ownerPhone: '11954879133',
      ownerEmail: 'gabriel.montanher@icloud.com',
      ownerCpf: '4126251138',
      breed: 'Maltês',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'pequeno',
      medications: 'Já precisou fazer fisioterapia — luxação e frouxidão na patela',
      feedingType: 'alimentacao_natural',
      feedingInstructions: 'A alimentação dele será enviada já pesada, e ele comerá apenas no horário do almoço',
      feedingTimesPerDay: '1 vez',
      feedingGramsPerMeal: '60',
      preferredActivities: 'Brinquedos de corda (cabo de guerra)',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Quarta, Sexta',
    },
  },
  {
    matricula: 'H003',
    data: {
      name: 'Ramiro',
      ownerName: 'Barbara Gomes',
      ownerPhone: '',
      breed: 'SRD',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'medio',
      feedingType: 'racao_seca',
    },
  },
  {
    matricula: 'H004',
    data: {
      name: 'Mel',
      ownerName: 'Jeniffer Lemes',
      ownerPhone: '11947185411',
      ownerEmail: 'jeniffer.lemes.2112@gmail.com',
      ownerCpf: '44306218880',
      breed: 'Border Collie',
      sex: 'femea',
      castrated: false,
      temperament: 'muita-energia',
      size: 'medio',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '3 vezes',
      feedingGramsPerMeal: '180',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Hotel',
    },
  },
  {
    matricula: 'C006',
    data: {
      name: 'Júpiter',
      ownerName: 'Gabriela Bittencourt',
      ownerPhone: '11986119285',
      ownerEmail: 'gabittencourtc@hotmail.com',
      ownerCpf: '42815015846',
      breed: 'Dachshund',
      sex: 'macho',
      castrated: true,
      temperament: 'media-energia',
      size: 'pequeno',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '1 vez',
      feedingGramsPerMeal: '60',
      preferredActivities: 'Buscar bolinha',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Terça, Quinta',
    },
  },
  {
    matricula: 'D002',
    data: {
      name: 'Thifany',
      ownerName: 'Roselaine da Mota Felisberto',
      ownerPhone: '11997181503',
      ownerEmail: 'roselainefelisberto_sp@hotmail.com',
      ownerCpf: '18351300896',
      breed: 'Lhasa Apso',
      sex: 'femea',
      castrated: true,
      temperament: 'media-energia',
      size: 'pequeno',
      feedingType: 'mista',
      feedingInstructions: 'Ela gosta de frango desfiado, carne moída, peixe, carne desfiada',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '100',
      preferredActivities: 'Correr atrás de brinquedo',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche + Hotel',
    },
  },
  {
    matricula: 'D003',
    data: {
      name: 'Jack Sparrow',
      ownerName: 'Ana Gabriela Monteiro Santos Warkentin',
      ownerPhone: '11992622142',
      ownerEmail: 'Ana.gabriela.m.santos@gmail.com',
      ownerCpf: '400.911.278-66',
      breed: 'SRD',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'medio',
      allergies: 'Diarreia com ração no café da manhã — suspensa, alimentação natural',
      feedingType: 'alimentacao_natural',
      feedingInstructions: 'Manhã: 1 ovo cozido. Almoço: metade do pacote de alimentação natural congelada (tirar do congelador no dia anterior). Jantar: outra metade.',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '375',
      preferredActivities: 'Bolinha, pular, correr e carrinho',
      vetName: 'Dra Alessan (prevent4pet): 11 95049-2308',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Hotel',
    },
  },
  {
    matricula: 'D004',
    data: {
      name: 'Annie Bonny',
      ownerName: 'Ana Gabriela Monteiro Santos Warkentin',
      ownerPhone: '11992622142',
      ownerEmail: 'Ana.gabriela.m.santos@gmail.com',
      ownerCpf: '400.911.278-66',
      breed: 'SRD',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'medio',
      allergies: 'Diarreia com ração no café da manhã — suspensa, alimentação natural',
      feedingType: 'alimentacao_natural',
      feedingInstructions: 'Manhã: 1 ovo cozido. Almoço: metade do pacote de alimentação natural congelada (tirar do congelador no dia anterior). Jantar: outra metade.',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '375',
      preferredActivities: 'Bolinha, pular, correr e carrinho',
      vetName: 'Dra Alessan (prevent4pet): 11 95049-2308',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Hotel',
    },
  },
  {
    matricula: 'D005',
    data: {
      name: 'Betina',
      ownerName: 'Eunira Keiko',
      ownerPhone: '',
      breed: 'SRD',
      sex: 'femea',
      castrated: true,
      temperament: 'media-energia',
      size: 'pequeno',
      feedingType: 'racao_seca',
    },
  },
  {
    matricula: 'C007',
    data: {
      name: 'Tobias',
      ownerName: 'Silvana Cobo',
      ownerPhone: '11971521665',
      ownerEmail: 'Cobosilvana28@gmail.com',
      ownerCpf: '6061452810',
      breed: 'Shih Tzu',
      sex: 'macho',
      castrated: true,
      temperament: 'baixa-energia',
      size: 'pequeno',
      medications: 'Tem lama na vesícula',
      allergies: 'Não identificadas',
      feedingType: 'mista',
      feedingInstructions: 'Misturar a ração com pedaços de beterraba, carne moída...',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '40',
      preferredActivities: 'Dormir',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Terça, Quinta',
    },
  },
  {
    matricula: 'C008',
    data: {
      name: 'Maya',
      ownerName: 'Leonardo Gattermayer',
      ownerPhone: '17996332736',
      ownerEmail: 'leogattermayer@hotmail.com',
      ownerCpf: '41725586827',
      breed: 'Golden Retriever',
      sex: 'femea',
      castrated: true,
      temperament: 'muita-energia',
      size: 'grande',
      allergies: 'Cloro (piscina) — banho obrigatório após contato com piscina',
      feedingType: 'racao_seca',
      feedingInstructions: 'Duas refeições: manhã cedo e por volta das 20h',
      feedingTimesPerDay: '2 vezes',
      feedingGramsPerMeal: '200',
      preferredActivities: 'Buscar bolinha',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: false,
      allowPhotos: true,
      serviceType: 'Creche + Hotel',
      scheduledDays: 'Sexta',
    },
  },
  {
    matricula: 'C009',
    data: {
      name: 'Bucky',
      ownerName: 'Lucas de Carvalho Xavier',
      ownerPhone: '11973360863',
      ownerEmail: 'Lucas_xavier@icloud.com',
      ownerCpf: '41763354830',
      breed: 'Golden Retriever',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'grande',
      medications: 'Dermatites',
      allergies: 'Perfume',
      feedingTimesPerDay: '3 vezes',
      feedingGramsPerMeal: '150',
      preferredActivities: 'Buscar bolinha e brinquedos de morder',
      vetName: 'Autorizo veterinário parceiro AU-Ê',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Segunda, Quarta',
    },
  },
  {
    matricula: 'C010',
    data: {
      name: 'Leonardo',
      ownerName: 'Thaís Gabrielly Pereira Mançano',
      ownerPhone: '11960884582',
      ownerEmail: 'mancanothais@gmail.com',
      ownerCpf: '36758737810',
      breed: 'Golden Retriever',
      sex: 'macho',
      castrated: true,
      temperament: 'muita-energia',
      size: 'grande',
      feedingType: 'racao_seca',
      feedingTimesPerDay: '4 vezes',
      feedingGramsPerMeal: '100',
      vetName: 'vitha',
      allowPool: true,
      allowPhotos: true,
      serviceType: 'Creche',
      scheduledDays: 'Segunda, Quarta',
    },
  },
]

async function main() {
  console.log(`\n🐾 Corrigindo ${updates.length} cadastros...\n`)
  let ok = 0
  let notFound = 0

  for (const { matricula, data } of updates) {
    const dog = await prisma.dog.findUnique({ where: { matricula } })
    if (!dog) {
      console.log(`❌ Não encontrado: ${matricula}`)
      notFound++
      continue
    }
    await prisma.dog.update({ where: { matricula }, data })
    console.log(`✅ ${matricula} — ${data.name} (${data.ownerName})`)
    ok++
  }

  console.log(`\n✅ ${ok} atualizados | ❌ ${notFound} não encontrados\n`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
