// eslint-disable-next-line @typescript-eslint/no-require-imports
const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

const dogs = [
  {
    name: 'Carla',
    ownerName: 'Sol',
    ownerPhone: '11991289694',
    ownerCpf: '36704848843',
    breed: 'Border Collie',
    sex: 'femea',
    castrated: true,
    size: 'Médio',
    temperament: 'Medianamente ativo',
    feedingType: 'seca',
    feedingTimesPerDay: '2',
    feedingGramsPerMeal: '160',
    preferredActivities: 'Correr e pular',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Hotel',
    notes: 'Matrícula: H001',
    isActive: true,
  },
  {
    name: 'Dory',
    ownerName: 'Valéria Bellato',
    ownerPhone: '11947746229',
    ownerCpf: '031.162.158-98',
    breed: 'Lhasa Apso',
    sex: 'femea',
    castrated: true,
    size: 'Médio',
    temperament: 'Muito ativo',
    feedingType: 'mista',
    feedingTimesPerDay: '1',
    feedingGramsPerMeal: '50',
    preferredActivities: 'Tudo que gostar',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Terça',
    notes: 'Matrícula: C001',
    isActive: true,
  },
  {
    name: 'Sirius Black',
    ownerName: 'Aline Porto',
    ownerPhone: '',
    breed: 'Pug',
    sex: 'macho',
    castrated: false,
    size: 'Pequeno',
    temperament: 'Muito ativo',
    feedingType: 'mista',
    feedingTimesPerDay: '3',
    allergies: 'Perfume de ambiente',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    notes: 'Matrícula: C002',
    isActive: true,
  },
  {
    name: 'Luna',
    ownerName: 'Tassia Gortari',
    ownerPhone: '11971572749',
    ownerCpf: '35680254859',
    breed: 'Maltês',
    sex: 'femea',
    castrated: true,
    size: 'Pequeno',
    temperament: 'Medianamente ativo',
    feedingType: 'mista',
    feedingTimesPerDay: '3',
    feedingGramsPerMeal: '25',
    medications: 'Dermatite',
    preferredActivities: 'Buscar bolinha',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Hotel',
    scheduledDays: 'Segunda',
    notes: 'Matrícula: H002',
    isActive: true,
  },
  {
    name: 'Baruc',
    ownerName: 'Debora Crippa',
    ownerPhone: '11945140568',
    ownerCpf: '35382667681',
    breed: 'Golden Retriever',
    sex: 'macho',
    castrated: true,
    size: 'Grande',
    temperament: 'Medianamente ativo',
    feedingType: 'seca',
    feedingTimesPerDay: '2',
    feedingGramsPerMeal: '240',
    medications: 'Alergia alimentar',
    allergies: 'Alimento específico',
    preferredActivities: 'Jogar e brincar',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Hotel',
    scheduledDays: 'Quarta',
    notes: 'Matrícula: D001',
    isActive: true,
  },
  {
    name: 'Theodore',
    ownerName: 'Vitória Pereira',
    ownerPhone: '11971269868',
    ownerCpf: '431.548.198-00',
    breed: 'Shih Tzu',
    sex: 'macho',
    castrated: true,
    size: 'Médio',
    temperament: 'Muito ativo',
    feedingType: 'seca',
    feedingInstructions: 'Ração especial prescrita',
    feedingTimesPerDay: '3',
    feedingGramsPerMeal: '100',
    medications: 'Obesidade',
    preferredActivities: 'Buscar bolinha',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Terça, Quinta',
    notes: 'Matrícula: C003',
    isActive: true,
  },
  {
    name: 'Romain',
    ownerName: 'Gabriel Mc',
    ownerPhone: '11954879133',
    ownerCpf: '4126251138',
    breed: 'SRD',
    sex: 'macho',
    temperament: 'Muito ativo',
    feedingType: 'mista',
    feedingTimesPerDay: '1',
    feedingGramsPerMeal: '200',
    allergies: 'Formigas',
    preferredActivities: 'Atividades com pessoas',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Quarta, Sexta',
    notes: 'Matrícula: C004',
    isActive: true,
  },
  {
    name: 'Theo',
    ownerName: 'Gabriel Mc',
    ownerPhone: '11954879133',
    ownerCpf: '4126251138',
    breed: 'Bulldog',
    sex: 'macho',
    temperament: 'Muito ativo',
    feedingType: 'natural',
    feedingInstructions: 'Alimentação natural especial',
    feedingTimesPerDay: '1',
    feedingGramsPerMeal: '80',
    preferredActivities: 'Ele gosta de brincar',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Quarta, Sexta',
    notes: 'Matrícula: C005',
    isActive: true,
  },
  {
    name: 'Ramiro',
    ownerName: 'Barbara Ghetti',
    ownerPhone: '',
    breed: 'SRD',
    sex: 'macho',
    castrated: true,
    size: 'Médio',
    temperament: 'Muito ativo',
    feedingType: 'seca',
    notes: 'Matrícula: H003',
    isActive: true,
  },
  {
    name: 'Mel',
    ownerName: 'Jenniffer Leite',
    ownerPhone: '11947185411',
    ownerCpf: '44306218880',
    breed: 'SRD',
    feedingType: 'seca',
    feedingGramsPerMeal: '180',
    allowPool: true,
    allowPhotos: true,
    notes: 'Matrícula: H004',
    isActive: true,
  },
  {
    name: 'Júpiter',
    ownerName: 'Gabriela B.',
    ownerPhone: '11986119285',
    ownerCpf: '42815015846',
    breed: 'Dachshund',
    sex: 'macho',
    temperament: 'Muito ativo',
    feedingType: 'seca',
    feedingTimesPerDay: '1',
    feedingGramsPerMeal: '60',
    preferredActivities: 'Buscar bolinha',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Terça, Quinta',
    notes: 'Matrícula: C006',
    isActive: true,
  },
  {
    name: 'Thifany',
    ownerName: 'Roselaline',
    ownerPhone: '11987181503',
    ownerCpf: '18351300896',
    breed: 'Lhasa Apso',
    sex: 'femea',
    temperament: 'Muito ativo',
    feedingType: 'mista',
    feedingTimesPerDay: '2',
    preferredActivities: 'Gosta de atividades',
    allowPool: true,
    allowPhotos: true,
    notes: 'Matrícula: D002',
    isActive: true,
  },
  {
    name: 'Jack Sparrow',
    ownerName: 'Ana Gabriela',
    ownerPhone: '11982622142',
    ownerCpf: '400.911.278-66',
    breed: 'SRD',
    sex: 'macho',
    temperament: 'Muito ativo',
    feedingType: 'natural',
    feedingInstructions: 'De manhã alimento natural',
    feedingTimesPerDay: '2',
    feedingGramsPerMeal: '375',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Hotel',
    notes: 'Matrícula: D003',
    isActive: true,
  },
  {
    name: 'Annie Bone',
    ownerName: 'Ana Gabriela',
    ownerPhone: '11982622142',
    ownerCpf: '400.911.278-66',
    breed: 'SRD',
    sex: 'femea',
    temperament: 'Muito ativo',
    feedingType: 'natural',
    feedingInstructions: 'De manhã alimento natural',
    feedingTimesPerDay: '2',
    feedingGramsPerMeal: '375',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Hotel',
    notes: 'Matrícula: D004',
    isActive: true,
  },
  {
    name: 'Betina',
    ownerName: 'Eurira Keiko',
    ownerPhone: '',
    breed: 'SRD',
    sex: 'femea',
    temperament: 'Muito ativo',
    feedingType: 'seca',
    allowPool: true,
    allowPhotos: true,
    notes: 'Matrícula: D005',
    isActive: true,
  },
  {
    name: 'Tobias',
    ownerName: 'Silvana Costa',
    ownerPhone: '11971521665',
    ownerCpf: '6061452810',
    breed: 'Shih Tzu',
    sex: 'macho',
    castrated: true,
    size: 'Pequeno',
    temperament: 'Calmo',
    feedingType: 'mista',
    feedingInstructions: 'Mistura alimento',
    feedingTimesPerDay: '2',
    feedingGramsPerMeal: '40',
    medications: 'Tem lama/problema de saúde',
    allergies: 'Não come o que não conhece',
    preferredActivities: 'Dormir',
    serviceType: 'Creche',
    scheduledDays: 'Terça, Quinta',
    notes: 'Matrícula: C007',
    isActive: true,
  },
  {
    name: 'Maya',
    ownerName: 'Leonardo C.',
    ownerPhone: '',
    breed: 'SRD',
    feedingType: 'seca',
    feedingInstructions: 'Ela come quantidade específica',
    feedingTimesPerDay: '3',
    feedingGramsPerMeal: '200',
    allergies: 'Cloro da piscina',
    preferredActivities: 'Buscar bolinha',
    allowPool: false,
    allowPhotos: true,
    serviceType: 'Creche',
    notes: 'Matrícula: C008 — Não pode piscina (alergia a cloro)',
    isActive: true,
  },
  {
    name: 'Bucky',
    ownerName: 'Lucas de C.',
    ownerPhone: '11973360863',
    ownerCpf: '41763354038',
    breed: 'Golden Retriever',
    sex: 'macho',
    size: 'Grande',
    temperament: 'Muito ativo',
    feedingTimesPerDay: '3',
    feedingGramsPerMeal: '150',
    medications: 'Dermatite',
    allergies: 'Perfume',
    preferredActivities: 'Buscar bolinha',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Segunda',
    notes: 'Matrícula: C009',
    isActive: true,
  },
  {
    name: 'Gorlando',
    ownerName: 'Thaís Gabriela',
    ownerPhone: '11960884582',
    ownerCpf: '36287537818',
    breed: 'Golden Retriever',
    sex: 'macho',
    temperament: 'Muito ativo',
    feedingType: 'seca',
    preferredActivities: 'Buscar bolinha',
    allowPool: true,
    allowPhotos: true,
    serviceType: 'Creche',
    scheduledDays: 'Segunda',
    notes: 'Matrícula: C010',
    isActive: true,
  },
]

async function main() {
  console.log(`\n🐾 Importando ${dogs.length} cães...\n`)
  let created = 0
  let skipped = 0

  for (const dog of dogs) {
    const existing = await prisma.dog.findFirst({
      where: { name: dog.name, ownerName: dog.ownerName },
    })

    if (existing) {
      console.log(`⏭  Já existe: ${dog.name} (${dog.ownerName})`)
      skipped++
    } else {
      await prisma.dog.create({ data: dog })
      console.log(`✅ Criado: ${dog.name} (${dog.ownerName}) — ${dog.notes}`)
      created++
    }
  }

  console.log(`\n✅ ${created} criados | ⏭ ${skipped} ignorados\n`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
